# Generated by Django 4.2.11 on 2026-05-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dropoff_address', models.TextField()),
                ('dropoff_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dropoff_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('base_fare', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet Balance'), ('cash', 'Cash'), ('card', 'Card')], default='wallet', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('requesting', 'Requesting Driver'), ('searching', 'Searching for Driver'), ('accepted', 'Driver Accepted'), ('arrived', 'Driver Arrived'), ('ongoing', 'Trip in Progress'), ('completed', 'Completed'), ('cancelled_by_student', 'Cancelled by Student'), ('cancelled_by_driver', 'Cancelled by Driver'), ('no_driver_found', 'No Driver Found')], default='requesting', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='bookings.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
